items = [
    {
        '_id': '1',
        'name': 'Burton Flight Attendant Camber Snowboard',
        'image': '/images/burton_flight_attendant_camber.jpg',
        'description':
        'Designed to be a terrain-slaying alternative to more traditional twin shapes, the mens Burton Flight Attendant Snowboard is a free spirit that dissects both pow and hard-pack with equal precision.',
        'brand': 'Burton',
        'category': 'Snowboards',
        'price': 579.95,
        'availableInStock': 20,
        'rating': 5.0,
        'reviews': 22,
    },
    {
        '_id': '2',
        'name': 'Burton Custom X Flying V Snowboard',
        'image': '/images/burton_custom_x_flying_v.jpg',
        'description':
        'Burton Custom X Snowboard has repeatedly delivered for snowboardings most demanding riders due to precise design and powerful drive.',
        'brand': 'Burton',
        'category': 'Snowboards',
        'price': 799.95,
        'availableInStock': 5,
        'rating': 4.0,
        'reviews': 18,
    },
    {
        '_id': '3',
        'name': 'Capita Mercury Snowboard',
        'image': '/images/capita_mercury.jpg',
        'description':
        'This award-winning series is renowned for all-terrain versatility from powder and kickers to side hits and laps around the park.',
        'brand': 'Capita',
        'category': 'Snowboards',
        'price': 599.99,
        'availableInStock': 10,
        'rating': 5.0,
        'reviews': 42,
    },
    {
        '_id': '4',
        'name': 'Capita Ultralight Powder Displacement Snowboard',
        'image': '/images/capita_ultralight_powder_displacement.jpg',
        'description':
        'A buoyant, ultra-lightweight Surflite 3.0 Core™ combined with a Surf Rocker camber profile and broad-shouldered shapes all work together to create zero-gravity floatation on top of even the deepest snow.',
        'brand': 'Capita',
        'category': 'Snowboards',
        'price': 618.95,
        'availableInStock': 15,
        'rating': 3.5,
        'reviews': 29,
    },
    {
        '_id': '5',
        'name': 'Arbor Westmark Camber Snowboard',
        'image': '/images/arbor_westmark_camber.jpg',
        'description':
        'The Westmark is your key to freestyle progression. Its medium flex makes for a lively pop, and a reliable and responsive ride all over the mountain.',
        'brand': 'Arbor',
        'category': 'Snowboards',
        'price': 469.99,
        'availableInStock': 11,
        'rating': 4.5,
        'reviews': 30,
    },
    {
        '_id': '6',
        'name': 'Arbor Wasteland Camber Snowboard',
        'image': '/images/arbor_wasteland_camber.jpg',
        'description':
        'The Wasteland is Arbor’s flagship mountain twin. The 4point System Camber is the optimal setup at speed, through steeps and deep carves. This mountain twin is fully capable.',
        'brand': 'Arbor',
        'category': 'Snowboards',
        'price': 756.95,
        'availableInStock': 7,
        'rating': 3.2,
        'reviews': 19,
    },
]
